export const compatibilityQuestions = [
  { key: "budget", category: "Бюджет", label: "Какой бюджет на вашу долю?" },
  { key: "districts", category: "Районы", label: "Какие районы подходят?" },
  { key: "moveInDate", category: "Дата въезда", label: "Когда вы готовы въехать?" },
  { key: "leaseMonths", category: "Срок", label: "На какой срок планируете аренду?" },
  { key: "sleep", category: "Режим сна", label: "Какой у вас режим сна?" },
  { key: "noise", category: "Шум", label: "Какой уровень шума комфортен?" },
  { key: "guests", category: "Гости", label: "Как часто бывают гости?" },
  { key: "parties", category: "Вечеринки", label: "Как вы относитесь к вечеринкам?" },
  { key: "smoking", category: "Курение", label: "Курите ли вы?" },
  { key: "alcohol", category: "Алкоголь", label: "Как вы относитесь к алкоголю дома?" },
  { key: "pets", category: "Животные", label: "Есть ли у вас животные?" },
  { key: "cleanliness", category: "Уборка", label: "Насколько важен порядок?" },
  { key: "cooking", category: "Готовка", label: "Как часто вы готовите?" },
  { key: "sharedProducts", category: "Общие продукты", label: "Готовы ли делить общие продукты?" },
  { key: "remoteWork", category: "Работа", label: "Как часто работаете из дома?" },
  { key: "temperature", category: "Температура", label: "Какую температуру предпочитаете?" },
  { key: "privateSpace", category: "Личное пространство", label: "Насколько важно личное пространство?" },
  { key: "commonZones", category: "Общие зоны", label: "Как используете общие зоны?" },
  { key: "sociability", category: "Общительность", label: "Насколько вы общительны дома?" },
  { key: "leisure", category: "Совместный досуг", label: "Какой досуг вам интересен?" },
] as const;
