"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Sparkles } from "lucide-react";
import { compatibilityQuestions } from "@/lib/compatibility/questions";
import { getRepository } from "@/lib/repositories";

const choices: Record<string, string[]> = {
  budget: ["До 20 000 ₽", "20 000–30 000 ₽", "30 000–45 000 ₽"], districts: ["Центр", "Фестивальный", "Юбилейный", "Готов рассмотреть любой"], moveInDate: ["В течение месяца", "Через 1–3 месяца", "Пока изучаю варианты"], leaseMonths: ["3–6 месяцев", "6–12 месяцев", "От года"], sleep: ["Рано ложусь", "Поздно ложусь", "Гибкий режим"], noise: ["Люблю тишину", "Умеренный фон", "Шум не мешает"], guests: ["Почти никогда", "Иногда", "Часто"], parties: ["Не люблю", "Иногда можно", "Люблю"], smoking: ["Не курю", "Иногда", "Курю"], alcohol: ["Не пью дома", "Иногда", "Спокойно отношусь"], pets: ["Нет животных", "Есть кошка", "Есть собака"], petTolerance: ["Только кошки", "Только собаки", "Готов(а) к любым", "Против животных"], cleanliness: ["Главное — чтобы было чисто", "Умеренный порядок", "Порядок не важен"], cooking: ["Почти не готовлю", "Несколько раз в неделю", "Готовлю часто"], sharedProducts: ["Да, удобно делить", "Только по договорённости", "Предпочитаю отдельно"], remoteWork: ["Не работаю дома", "Иногда", "Почти всегда"], temperature: ["Прохладно", "Средняя", "Тепло"], privateSpace: ["Очень важно", "В меру", "Люблю общение"], commonZones: ["Тихие общие зоны", "По-разному", "Много времени вместе"], sociability: ["Мне нужно уединение", "Баланс", "Люблю компанию"], leisure: ["Кино и книги", "Спорт и прогулки", "Игры и встречи"],
};

export function CompatibilityWizard() {
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Record<string, string>>({}); const [saved, setSaved] = useState(false); const question = compatibilityQuestions[step]; const options = choices[question.key] ?? ["Да", "Иногда", "Нет"];
  const progress = Math.round(((step + 1) / compatibilityQuestions.length) * 100);
  const choose = async (answer: string) => { setAnswers((current) => ({ ...current, [question.key]: answer })); await getRepository().saveAnswer({ questionKey: question.key, answer, importance: 3 }); setSaved(false); if (step < compatibilityQuestions.length - 1) setStep((current) => current + 1); else setSaved(true); };
  const summary = useMemo(() => Object.keys(answers).length, [answers]);
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><section className="surface-card p-5 sm:p-8"><div className="flex items-center justify-between text-xs font-bold text-muted-foreground"><span>Вопрос {step + 1} из {compatibilityQuestions.length}</span><span>{progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-surface-muted"><div className="h-full rounded-full bg-[hsl(var(--accent))] transition-all" style={{ width: `${progress}%` }} /></div><p className="mt-10 text-[11px] font-extrabold uppercase tracking-[0.12em] text-[hsl(var(--accent-hover))]">{question.category}</p><h2 className="mt-3 text-2xl font-extrabold tracking-[-0.04em]">{question.label}</h2><div className="mt-8 grid gap-3">{options.map((option) => <button type="button" key={option} onClick={() => void choose(option)} className={`flex min-h-14 items-center justify-between rounded-[16px] border px-4 text-left text-sm font-bold transition-colors hover:border-[hsl(var(--accent-hover))] hover:bg-[hsl(var(--accent-soft))] ${answers[question.key] === option ? "border-[hsl(var(--accent-hover))] bg-[hsl(var(--accent-soft))]" : "bg-surface"}`}><span>{option}</span>{answers[question.key] === option ? <Check className="size-4 text-[hsl(var(--accent-hover))]" /> : null}</button>)}</div><div className="mt-8 flex items-center justify-between"><button type="button" disabled={step === 0} onClick={() => setStep((current) => Math.max(0, current - 1))} className="inline-flex items-center gap-2 rounded-full border px-4 py-2.5 text-xs font-extrabold disabled:opacity-40"><ArrowLeft className="size-4" /> Назад</button>{step < compatibilityQuestions.length - 1 ? <button type="button" onClick={() => setStep((current) => current + 1)} className="inline-flex items-center gap-2 rounded-full bg-foreground px-4 py-2.5 text-xs font-extrabold text-background">Пропустить <ArrowRight className="size-4" /></button> : null}</div></section><aside className="space-y-4"><div className="rounded-[20px] bg-foreground p-5 text-background"><Sparkles className="size-5 text-[hsl(var(--accent))]" /><p className="mt-4 text-sm font-extrabold">Зачем это нужно</p><p className="mt-2 text-xs leading-5 text-background/65">Чем точнее ответы, тем понятнее будут совпадения и спорные места в будущей группе.</p></div><div className="surface-card p-5"><p className="text-xs font-extrabold">Заполнено</p><p className="mt-2 text-3xl font-extrabold text-[hsl(var(--accent-hover))]">{summary} / 20</p><p className="mt-1 text-xs text-muted-foreground">Ответы сохраняются автоматически.</p>{saved ? <p className="mt-4 rounded-[12px] bg-[hsl(var(--accent-soft))] p-3 text-xs font-bold">Анкета готова — профиль обновлён.</p> : null}</div></aside></div>;
}
